builds:
- env:
  - CGO_ENABLED=0
  hooks:
    # Install upx first, https://github.com/upx/upx/releases
    post: ./hack/compress.sh
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - 386
  ldflags:
    - -s -w -X github.com/stitchfix/codeowners-validator/pkg/version.version={{.Version}} -X  github.com/stitchfix/codeowners-validator/pkg/version.commit={{.ShortCommit}} -X github.com/stitchfix/codeowners-validator/pkg/version.buildDate={{.Date}}
  # List of combinations of GOOS + GOARCH + GOARM to ignore.
  # Default is empty.
  ignore:
    - goos: darwin
      goarch: 386
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

dockers:
  - dockerfile: Dockerfile
    binaries:
      - codeowners-validator
    image_templates:
      - "stitchfix/codeowners-validator:latest"
      - "stitchfix/codeowners-validator:{{ .Tag }}"
      - "stitchfix/codeowners-validator:v{{ .Major }}.{{ .Minor }}"
